baseURL = "https://www.den3tsou.com/"
languageCode = "en-us"
title = "Den Tsou"
theme = "ananke"
googleAnalytics= "G-G2R30C6FRT"

[params]
  twitter = "https://twitter.com/den3tsou"
  github = "https://github.com/den3tsou"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
